On branch main  Your branch is up-to-date with 'origin/main'.
 Changes to be committed:
	modified:   examples/saving_and_recalling_data/amp 1/grid.npz
	modified:   examples/saving_and_recalling_data/amp 1/optical_assembly.npz
	modified:   examples/saving_and_recalling_data/amp 1/pulse.npz
	modified:   pyLaserPulse/optical_assemblies.py

Bugfix:
AttributeError: 'numpy.ndarray' object has no attribute 'append'
Caused by conversion of pulse.output to numpy array in
optical_assemblies.py. Occurred when subsequent optical assemblies had
taps (or other components sending fields to pulse.output).

This has been tested for sm_fibre_amplifier assemblies with active
and passive components, but not for fibre laser assemblies.